### ISSUE TITLE
ENH: Money system

### ISSUE THREAD

**Issue by iquelli** [TiagoFar78/PrisonEscape#108]
Create a currency system for police to purchase items. This would allow police players to buy necessary gear and equipment.

**Comment by iquelli** [comment]
Thinking for this version to spawn police with an x amount of balance they can spend. And then for 1.0 we work on the missions.
@TiagoFar78  what do you think?

**Comment by TiagoFar78** [comment]
I think that it is perfect. Missions are going to be hard work, better leave it for later.
