### ISSUE TITLE
ENH: Teleport in and out of maze

### ISSUE THREAD

**Issue by iquelli** [TiagoFar78/PrisonEscape#120]
Subtask of #57 

**Describe the solution you'd like**
Teleport players in and out of maze at night when they select to do so.
Also teleport players out of maze when the day starts.

**Comment by TiagoFar78** [comment]
That is part of #48 , secret passages will give players the ability to move arround.

**Comment by TiagoFar78** [comment]
> Also teleport players out of maze when the day starts.

Why? The maze is supposed to be accessible when they are in their cells.

**Comment by iquelli** [comment]
> s.

thought that in during the day they had to be out of it

**Comment by TiagoFar78** [comment]
They can be there any time they want.
