### ISSUE TITLE
INV: Rename PrisonEscape objects

### ISSUE THREAD

**Issue by TiagoFar78** [TiagoFar78/PrisonEscape#130]
**Describe the bug**
There are some lines that are too long. Just a simple definition of an Hashtable with key and value PrisonEscapeLocation takes a lot of space.

**Expected behavior**
Lines should be smaller.

**Screenshots**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/01dbb9cb-ea7d-40e8-9be3-48c81334a8eb)
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/7bffbd49-a470-4e13-80bf-d330e9d2459c)

**Additional context**
Probably it is a good idea to rename every object that has "PrisonEscape" as prefix, in order to make lines look cleaner. Also There is no reason to name objects like that because every object created inside this plugin is supposed to be related to the Prison Escape.

**Comment by iquelli** [comment]
Leave this one to do after everything else is done

**Comment by TiagoFar78** [comment]
> Leave this one to do after everything else is done

I am planning to do this as soon as nobody is working on anything. It would be nice to make these changes as soon as possible, but it would cause compilation problems and maybe some merge conflicts for PR's that are open right now.

**Comment by TiagoFar78** [comment]
It should be a good idea to remove PrisonEscapeLocation and use Location from bukkit since they are basically the same.
