### ISSUE TITLE
INV: Managers are not being initialized in plugin start

### ISSUE THREAD

**Issue by TiagoFar78** [TiagoFar78/PrisonEscape#133]
**Describe the bug**
The ConfigManager and the MessageLanguageManager are being initialized when they are needed for the first time. For example when a command is issued. This are supposed to be heavy operations so they should happen during plugin enabling.

**Expected behavior**
Initialize heavy managers in plugin enabling.

**Additional context**
It would be nice if a message was sent to the console saying that they were successfully initialized.

**Comment by iquelli** [comment]
Yeah that would be better
