### ISSUE TITLE
BUG: Iron bars not connecting

### ISSUE THREAD

**Issue by TiagoFar78** [TiagoFar78/PrisonEscape#172]
**Describe the bug**
Iron bars should connect to adjacent blocks.

**Expected behavior**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/1eb421c3-d617-4b5c-a77b-058831fceca6)

**Screenshots**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/41ac5d16-2b74-4981-93a5-44b41820f0e7)

**Comment by iquelli** [comment]
I have tried force updating them after creating them, but it does not seem to be working. Can't figure out why this happens
