### ISSUE TITLE
ENH: Implement crafting menu

### ISSUE THREAD

**Issue by TiagoFar78** [TiagoFar78/PrisonEscape#44]
Implement a menu for prisioners to craft new items using the ones they already have.

**Comment by ana-mc-almeida** [comment]
Hi! I would like to work on this issue. 
Can you give more specifications on what the crafting menu should look like?

**Comment by TiagoFar78** [comment]
This is what the menu will look like when opened.
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/450a16a7-a645-409e-96ba-564da0758c1c)

And when the player selects an item to be crafted the resources for that item will be shown as well as a wool to allow the player to craft the item. Here is an example for metal spoon (golden shovel in minecraft).
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/ff954c51-be56-4387-beaa-572e11213eea)

This is an example of what the wool looks like when the player has enough resources.
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/bf745b30-3c85-4ccb-8809-3bda85115888)

Consider this only as an example. This means you can change the menu and everything you want if you think that it will be a positive change.

**Comment by ana-mc-almeida** [comment]
Hi @TiagoFar78,I won't have the time to work on this issue. Could you please unassign me? Thank you!
