### ISSUE TITLE
ENH: Implement police kit

### ISSUE THREAD

**Issue by TiagoFar78** [TiagoFar78/PrisonEscape#50]
Create a kit for police. Create interactions for the items in the kit.

**Comment by TiagoFar78** [comment]
There is another item that is needed. An item that when clicked will open the shop menu. The interaction is not supposed to be done in this PR, but the item creation is.

**Comment by iquelli** [comment]
also need to add a  book to the kit

**Comment by TiagoFar78** [comment]
This kit should contain an item to open cameras when police team has set up at least one. #144
