### ISSUE TITLE
ENH: Implement missions

### ISSUE THREAD

**Issue by TiagoFar78** [TiagoFar78/PrisonEscape#58]
Create some missions that police have to do in order to receive money to buy items.

**Comment by iquelli** [comment]
Task ideas: 
-
-
-

**Comment by TiagoFar78** [comment]
You can look for mission ideas here #125

**Comment by iquelli** [comment]
Think we should part this issue into sub-issues

**Comment by TiagoFar78** [comment]
Missions list should be displayed on the scoreboard. There is no space for an item in the inventory in this moment.

**Comment by TiagoFar78** [comment]
There is now space again in the hotbar for the MissionItem.

Regarding the ideas given for the missions, all of them have the problem of being related to the world. This means that guards can complete the missions while keeping an eye on the prisoners. This is not supposed to happen; guards should not be able to catch prisoners while attending to their missions. Additionally, it is much more difficult to implement missions that are related to the physical world.

To solve this problem, the missions will be small challenges done through a menu. However, each mission must be completed in a specific region to force guards to move around the prison to earn money.
