### ISSUE TITLE
BUG: Countdown for game to start appears even after using for 

### ISSUE THREAD

**Issue by iquelli** [TiagoFar78/PrisonEscape#87]
Example:
![image](https://github.com/TiagoFar78/PrisonEscape/assets/93059659/17305e63-b597-4652-b0bb-b5ea98043d8f)

**Comment by iquelli** [comment]
error generated at the end of the countdown: 

![image](https://github.com/TiagoFar78/PrisonEscape/assets/93059659/c3eac449-ff81-42dd-9812-7b9ceabb3f3c)

**Comment by TiagoFar78** [comment]
This error doesn't happen to me when I use forcestart. Have you compiled the latest version? Chech issue #74 

The error in the photo is not related to the same thing and I have fixed it already in the branch I am working on right now.

**Comment by TiagoFar78** [comment]
> I have fixed it already in the branch I am working on right now.

This is now solved by PR #80.
