### ISSUE TITLE
DOC: Ugly formatter settings.

### ISSUE THREAD

**Issue by TiagoFar78** [TiagoFar78/PrisonEscape#99]
**Describe the bug**
This issue will be useful to make reference to every ugly aspect of the formatter. This issue is not to be solved until every ugly aspect of formatter has been taken into consideration. This isssue will be a work in progress where every ugly aspect of the formatter should be pointed.

If you want to post something here follow this template:

**Screenshots**
If applicable, add screenshots to help explain what you think is ugly.

**Expected behavior**
Make it look better and show us with a screen shot or code snipet.

**Additional context**
If you have anything else to say, say it here.

**Comment by TiagoFar78** [comment]
**Screenshots**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/b6689c1d-ac89-48cb-b864-08010d840d44)

**Expected behavior**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/76c7954a-0ea7-444a-9226-2289097f4206)

**Comment by TiagoFar78** [comment]
**Screenshots**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/f80492f1-09af-427a-891a-0b9e60772693)

**Expected behavior**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/78aba5a4-6491-4b6d-945e-e74b5f1aa895)

**Comment by iquelli** [comment]
Prob have to touch up some settings.

I feel like this one looks okay tho:

> **Screenshots** ![image](https://private-user-images.githubusercontent.com/42421954/318216169-b7ae7df7-a2b3-4dd5-a7c3-252d1380550c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjgzMTksIm5iZiI6MTcxMTgyODAxOSwicGF0aCI6Ii80MjQyMTk1NC8zMTgyMTYxNjktYjdhZTdkZjctYTJiMy00ZGQ1LWE3YzMtMjUyZDEzODA1NTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE5NDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMGIyZTk0MmEwZjAzY2JhZDUwNDlmNjgyNDU0NWFlMzJiZDFlODM2YjI0OTgyYTNmMWEwNTVkMmQzMWJlMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKGAtfTveUKv3NLmbWQdWRyhp61ayDJ70cwJkhg7st0)
> 
> **Expected behavior** ![image](https://private-user-images.githubusercontent.com/42421954/318216132-78aba5a4-6491-4b6d-945e-e74b5f1aa895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjgzMTksIm5iZiI6MTcxMTgyODAxOSwicGF0aCI6Ii80MjQyMTk1NC8zMTgyMTYxMzItNzhhYmE1YTQtNjQ5MS00YjZkLTk0NWUtZTc0YjVmMWFhODk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE5NDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzY2MzFjNmEzOTY5ZWQzMGVjZWFlYzJmYzA4MjllYjc4MTAyYzI5ZGZmZDY4NTYwMTlkMjFkOGQzYTYwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yubN4gqHu4WKW2F-TXVJaNcVCImrgljyQ4_qKEjvxXc)

**Comment by TiagoFar78** [comment]
> I feel like this one looks okay tho:

Which one? I can't open the screen shots

**Comment by iquelli** [comment]
> > I feel like this one looks okay tho:
> 
> Which one? I can't open the screen shots

The second one

**Comment by TiagoFar78** [comment]
**Screenshots**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/0ed153f7-6f59-45b0-a4b2-ca4756e0a159)

**Expected behavior**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/7d160d0e-043d-4e5d-a488-a4e951f44e46)

**Comment by TiagoFar78** [comment]
**Screenshots**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/42097036-c833-4d1b-804c-d31e9937b7d6)


**Expected behavior**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/8bff2863-9dc7-4b4b-a69b-daa5e97f0416)

**Comment by TiagoFar78** [comment]
**Screenshots**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/b9941540-51c6-4b1c-a830-aa6d7b4c7905)


**Expected behavior**
![image](https://github.com/TiagoFar78/PrisonEscape/assets/42421954/37cdea5c-330b-4fb1-a4dd-f46d73f0b0be)

**Comment by TiagoFar78** [comment]
This issue was separated in different parts.
